version: '2.2'
services:
    rabbitmq:
        hostname: rabbit
        image: rabbitmq:3.7-management
        networks: 
            - network
        environment:
            - TCP_PORTS=15672, 5672
        ports:
            - "5672:5672"
    influxdb:
        image: influxdb
        tty: True
        networks: 
            - network
        environment:
            INFLUXDB_USER: tides
            INFLUXDB_USER_PASSWORD: TidesGoesUpAndDown
            INFLUXDB_DB: tidesmonitor
        volumes:
            - influxdb:/var/lib/influxdb

    grafana:
        image: grafana/grafana
        networks: 
            - network
        ports:
            - '3000:3000'
        links:
            - influxdb
        environment:
            GF_INSTALL_PLUGINS: 'grafana-worldmap-panel'
            GF_SECURITY_ADMIN_PASSWORD: admin
        volumes:
            - grafana:/var/lib/grafana

    worker:
        image: tidesmonitor
        build:
            context: .
        tty: True
        working_dir: /app
        networks: 
            - network
        volumes:
            - ./:/app
            - celery:/var/lib/celery
        links:
            - rabbitmq
        command: celery -A tides worker -E -c1 -l INFO -B

    monitor:
        image: tidesmonitor
        tty: True
        working_dir: /app
        volumes:
            - ./:/app
        command: python monitor/monitor.py
volumes:
    influxdb:
    grafana:
    celery:

networks:
    network:



  
